pragma Singleton

// island-dots — a Hyprland shell built around a morphing pill.
// Copyright (C) 2026 Siddhartha Mallavolu
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version. See LICENSE.

import Quickshell

// Every path the shell reads or writes, in one place.
//
// This exists because those paths used to be spelled out at each use
// site as `Quickshell.env("HOME") + "/island-dots/..."`, which hard-
// codes both the XDG layout and the name of the directory the repo
// was cloned into. A clone anywhere else came up with no palette, no
// GTK colours and no gestures, and nothing said why.
//
// Nothing here points into the repo. Generated files live under the
// state directory and the machine-specific matugen config is written
// by install.sh, so the shell never needs to know where the repo is.
Singleton {
    id: root

    readonly property string home: Quickshell.env("HOME")

    // Quickshell.env returns an empty string for an unset variable
    // rather than undefined, so an `||` chain would still pick it.
    function xdg(name, fallback) {
        const v = Quickshell.env(name);
        return (v && v.length > 0) ? v : root.home + fallback;
    }

    readonly property string configHome: xdg("XDG_CONFIG_HOME", "/.config")
    readonly property string stateHome:  xdg("XDG_STATE_HOME",  "/.local/state")
    readonly property string cacheHome:  xdg("XDG_CACHE_HOME",  "/.cache")

    readonly property string configDir: configHome + "/island"
    readonly property string stateDir:  stateHome + "/island"

    readonly property string settings:  configDir + "/settings.json"

    // Written by install.sh with absolute paths filled in, because
    // matugen's TOML cannot expand a variable.
    readonly property string matugenConfig: configDir + "/matugen.toml"

    // Generated by matugen on every wallpaper change. Kept out of the
    // repo: it is machine state, and a checkout is not writable on
    // every machine the shell might run on.
    readonly property string colors:    stateDir + "/colors.json"
    readonly property string wallpaper: stateDir + "/wallpaper"
}
