pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick

Singleton {
    id: root

    readonly property string dir: Config.wallpaper.directory
    readonly property string statePath: Paths.wallpaper

    property string current: ""
    property var list: []
    property bool busy: false

    // ── What the renderer can actually decode ────────────────────
    //
    // The scan used to offer every .webp it found whether or not Qt
    // could read one. Qt ships no WebP plugin of its own — it comes
    // from qt6-qtimageformats — so on a machine without that package
    // the picker listed wallpapers that rendered as an empty tile, and
    // setting one gave a blank desktop and a line in the log.
    //
    // Rather than hardcoding an answer, a one-pixel image of each
    // questionable format is decoded at startup and the format is
    // offered only if that worked. Install the package and the files
    // appear on the next scan, with nothing to configure.
    readonly property var probes: ({
        webp: "data:image/webp;base64,UklGRhoAAABXRUJQVlA4TA0AAAAvAAAAEAcQERGIiP4HAA=="
    })

    // jpg and png are built into Qt and never need checking.
    property var formats: ["jpg", "jpeg", "png"]

    // Number of files skipped because nothing here can display them,
    // so the settings page can say so instead of quietly omitting.
    property int unsupported: 0

    // Instantiator, not Repeater: a Repeater needs a visual parent to
    // instantiate into and this singleton has none, so its delegates
    // were never created and the probe never ran.
    Instantiator {
        model: Object.keys(root.probes)

        delegate: Image {
            required property var modelData

            source: root.probes[modelData]
            asynchronous: false
            cache: false

            onStatusChanged: {
                if (status === Image.Ready) {
                    if (root.formats.indexOf(modelData) === -1) {
                        
                        root.formats = root.formats.concat([modelData]);
                        root.refresh();
                    }
                } else if (status === Image.Error) {
                    // console.warn, not console.log: the log only
                    // carries warnings, and Qt has just emitted its
                    // own unexplained "Unsupported image format" for
                    // this probe. This is the line that says why.
                    console.warn("[Wallpaper] no decoder for ." + modelData
                        + " — install qt6-qtimageformats to use those"
                        + " wallpapers. They are left out of the picker"
                        + " rather than offered as blank tiles.");
                }
            }
        }
    }

    function set(path, force) {
        if (!path)
            return;

        if (path === current && force !== true) {
            // Same image: nothing to fade, but the palette may still
            // need regenerating after a scheme change.
            return;
        }

        current = path;
        stateFile.setText(path);
        generate(path);
    }

    function reapply() {
        if (current !== "") generate(current);
    }

    function next() {
        if (list.length === 0)
            return;
        const i = list.indexOf(current);
        set(list[(i + 1) % list.length]);
    }

    function previous() {
        if (list.length === 0)
            return;
        const i = list.indexOf(current);
        set(list[(i - 1 + list.length) % list.length]);
    }

    function random() {
        if (list.length === 0)
            return;
        set(list[Math.floor(Math.random() * list.length)]);
    }

    function refresh() {
        lister.running = true;
    }

    // Re-scan when the configured directory changes.
    onDirChanged: refresh()

    property string pending: ""

    function generate(path) {
        if (busy) {
            pending = path;
            return;
        }
        busy = true;
        watchdog.restart();
        matugen.command = [
            "matugen",
            // Generated by install.sh with this machine's absolute
            // paths filled in — matugen's TOML cannot expand one.
            "--config", Paths.matugenConfig,
            "image", path,
            "--source-color-index", "0",
            "-t", Config.wallpaper.scheme
        ];
        matugen.running = true;
    }

    FileView {
        id: stateFile
        path: root.statePath
        printErrors: false

        // Create the file (and its directory) if this is a first run.
        preload: true

        onLoaded: {
            const saved = stateFile.text().trim();
            if (saved !== "")
                root.current = saved;
        }
    }

    Process {
        id: lister
        running: true

        // Everything is listed, then split by whether this build can
        // decode it — so the count of skipped files is knowable rather
        // than the files merely being absent.
        command: [
            "sh", "-c",
            "find '" + root.dir + "' -type f "
            + "\\( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' "
            + "-o -iname '*.webp' -o -iname '*.avif' -o -iname '*.jxl' "
            + "\\) 2>/dev/null | sort"
        ]

        stdout: StdioCollector {
            onStreamFinished: {
                const out = this.text.trim();
                const all = out === "" ? [] : out.split("\n");

                const usable = all.filter(p => {
                    const dot = p.lastIndexOf(".");
                    if (dot < 0) return false;
                    return root.formats.indexOf(
                        p.slice(dot + 1).toLowerCase()) !== -1;
                });

                root.unsupported = all.length - usable.length;
                root.list = usable;

                // First run with nothing saved: take the first one.
                if (root.current === "" && root.list.length > 0)
                    root.set(root.list[0]);
            }
        }
    }

    // Optional rotation. 0 in the config disables it.
    Timer {
        running: Config.wallpaper.rotateMinutes > 0
        interval: Math.max(1, Config.wallpaper.rotateMinutes) * 60000
        repeat: true
        onTriggered: root.random()
    }

    // If matugen never exits — a bad image, a hung process — `busy`
    // would stay true and every later change would queue behind it
    // forever. Release the lock after 15s rather than wedging.
    Timer {
        id: watchdog
        interval: 15000
        onTriggered: {
            if (root.busy) {
                console.warn("[Wallpaper] matugen did not finish; releasing lock");
                root.busy = false;
                if (root.pending !== "") {
                    const next = root.pending;
                    root.pending = "";
                    root.generate(next);
                }
            }
        }
    }

    Process {
        id: matugen
        running: false

        onExited: function(code) {
            root.busy = false;
            watchdog.stop();
            if (code !== 0)
                console.warn("Wallpaper: matugen exited with", code);

            // Run whatever arrived while we were busy. Only the last
            // one matters — intermediate palettes would be overwritten
            // a moment later anyway.
            if (root.pending !== "") {
                const next = root.pending;
                root.pending = "";
                root.generate(next);
            }
        }

        stderr: StdioCollector {
            onStreamFinished: {
                if (this.text.trim() !== "")
                    console.warn("matugen:", this.text.trim());
            }
        }
    }

    IpcHandler {
        target: "wallpaper"

        function next(): void { root.next() }
        function previous(): void { root.previous() }
        function random(): void { root.random() }
        function refresh(): void { root.refresh() }
        function set(path: string): void { root.set(path) }
        function reapply(): void { root.reapply() }
        function current(): string { return root.current }
    }
}
